---
- name: web-server auto config
  hosts: webservers
  become: true
  tasks:

  - name: install module called python3-pip
    apt:
      force_apt_get: yes
      update_cache: yes
      name: python3-pip
      state: present

  - name: install module called docker.io
    apt:
      force_apt_get: yes
      name: docker.io
      state: present

  - name: install library called docker
    pip:
      name: docker
      state: present

  - name: install docker container called DVWA
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      published_ports: 80:80

  - name: enable docker service
    systemd:
      name: docker
      enabled: yes
